defmodule Countryguessr.Countries do
  @moduledoc """
  Valid country codes for the game.

  These codes match the ISO_A2 property from the frontend's countries.geojson.
  Includes standard ISO 3166-1 alpha-2 codes plus special codes for disputed
  territories (SYN_NORTHERN_CYPRUS, SYN_SOMALILAND).
  """

  @valid_codes MapSet.new([
                 "AE",
                 "AF",
                 "AL",
                 "AM",
                 "AO",
                 "AR",
                 "AT",
                 "AU",
                 "AZ",
                 "BA",
                 "BD",
                 "BE",
                 "BF",
                 "BG",
                 "BI",
                 "BJ",
                 "BN",
                 "BO",
                 "BR",
                 "BS",
                 "BT",
                 "BW",
                 "BY",
                 "BZ",
                 "CA",
                 "CD",
                 "CF",
                 "CG",
                 "CH",
                 "CI",
                 "CL",
                 "CM",
                 "CN",
                 "CO",
                 "CR",
                 "CU",
                 "CY",
                 "CZ",
                 "DE",
                 "DJ",
                 "DK",
                 "DO",
                 "DZ",
                 "EC",
                 "EE",
                 "EG",
                 "EH",
                 "ER",
                 "ES",
                 "ET",
                 "FI",
                 "FJ",
                 "FR",
                 "GA",
                 "GB",
                 "GE",
                 "GF",
                 "GH",
                 "GL",
                 "GM",
                 "GN",
                 "GQ",
                 "GR",
                 "GT",
                 "GW",
                 "GY",
                 "HN",
                 "HR",
                 "HT",
                 "HU",
                 "ID",
                 "IE",
                 "IL",
                 "IN",
                 "IQ",
                 "IR",
                 "IS",
                 "IT",
                 "JM",
                 "JO",
                 "JP",
                 "KE",
                 "KG",
                 "KH",
                 "KP",
                 "KR",
                 "KW",
                 "KZ",
                 "LA",
                 "LB",
                 "LK",
                 "LR",
                 "LS",
                 "LT",
                 "LU",
                 "LV",
                 "LY",
                 "MA",
                 "MD",
                 "ME",
                 "MG",
                 "MK",
                 "ML",
                 "MM",
                 "MN",
                 "MR",
                 "MT",
                 "MW",
                 "MX",
                 "MY",
                 "MZ",
                 "NA",
                 "NC",
                 "NE",
                 "NG",
                 "NI",
                 "NL",
                 "NO",
                 "NP",
                 "NZ",
                 "OM",
                 "PA",
                 "PE",
                 "PG",
                 "PH",
                 "PK",
                 "PL",
                 "PR",
                 "PS",
                 "PT",
                 "PY",
                 "QA",
                 "RO",
                 "RS",
                 "RU",
                 "RW",
                 "SA",
                 "SB",
                 "SC",
                 "SD",
                 "SE",
                 "SG",
                 "SI",
                 "SK",
                 "SL",
                 "SN",
                 "SO",
                 "SR",
                 "SS",
                 "SV",
                 "SY",
                 "SZ",
                 "TD",
                 "TG",
                 "TH",
                 "TJ",
                 "TL",
                 "TM",
                 "TN",
                 "TR",
                 "TT",
                 "TW",
                 "TZ",
                 "UA",
                 "UG",
                 "US",
                 "UY",
                 "UZ",
                 "VE",
                 "VN",
                 "VU",
                 "XK",
                 "YE",
                 "ZA",
                 "ZM",
                 "ZW",
                 # Disputed territories with special codes
                 "SYN_NORTHERN_CYPRUS",
                 "SYN_SOMALILAND"
               ])

  @doc """
  Returns true if the given code is a valid country code.
  """
  @spec valid?(String.t()) :: boolean()
  def valid?(code) when is_binary(code), do: MapSet.member?(@valid_codes, code)
  def valid?(_), do: false

  @doc """
  Returns the set of all valid country codes.
  """
  @spec all() :: MapSet.t(String.t())
  def all, do: @valid_codes

  @doc """
  Returns the total number of valid country codes.
  """
  @spec count() :: non_neg_integer()
  def count, do: MapSet.size(@valid_codes)
end
